-- Revert to TIMESTAMP (local time)

ALTER TABLE response_answers
ALTER COLUMN created_at TYPE TIMESTAMP,
ALTER COLUMN created_at SET DEFAULT NOW();

ALTER TABLE form_responses
ALTER COLUMN submitted_at TYPE TIMESTAMP,
ALTER COLUMN submitted_at SET DEFAULT NOW(),
ALTER COLUMN created_at TYPE TIMESTAMP,
ALTER COLUMN created_at SET DEFAULT NOW();

ALTER TABLE forms
ALTER COLUMN published_at TYPE TIMESTAMP;

ALTER TABLE flow_connections
ALTER COLUMN created_at TYPE TIMESTAMP,
ALTER COLUMN created_at SET DEFAULT NOW(),
ALTER COLUMN updated_at TYPE TIMESTAMP,
ALTER COLUMN updated_at SET DEFAULT NOW(),
ALTER COLUMN deleted_at TYPE TIMESTAMP;

ALTER TABLE questions
ALTER COLUMN created_at TYPE TIMESTAMP,
ALTER COLUMN created_at SET DEFAULT NOW(),
ALTER COLUMN updated_at TYPE TIMESTAMP,
ALTER COLUMN updated_at SET DEFAULT NOW(),
ALTER COLUMN deleted_at TYPE TIMESTAMP;
